# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tpmon_pb2 as tpmon__pb2


class ThroughputRendererStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.QueryPosition = channel.unary_unary(
        '/tpmon.ThroughputRenderer/QueryPosition',
        request_serializer=tpmon__pb2.QueryPositionRequest.SerializeToString,
        response_deserializer=tpmon__pb2.QueryPositionResponse.FromString,
        )
    self.SetPosition = channel.unary_unary(
        '/tpmon.ThroughputRenderer/SetPosition',
        request_serializer=tpmon__pb2.SetPositionRequest.SerializeToString,
        response_deserializer=tpmon__pb2.StatusResponse.FromString,
        )


class ThroughputRendererServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def QueryPosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ThroughputRendererServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'QueryPosition': grpc.unary_unary_rpc_method_handler(
          servicer.QueryPosition,
          request_deserializer=tpmon__pb2.QueryPositionRequest.FromString,
          response_serializer=tpmon__pb2.QueryPositionResponse.SerializeToString,
      ),
      'SetPosition': grpc.unary_unary_rpc_method_handler(
          servicer.SetPosition,
          request_deserializer=tpmon__pb2.SetPositionRequest.FromString,
          response_serializer=tpmon__pb2.StatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tpmon.ThroughputRenderer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
