# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tpmon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tpmon.proto',
  package='tpmon',
  syntax='proto3',
  serialized_pb=_b('\n\x0btpmon.proto\x12\x05tpmon\"\x16\n\x14QueryPositionRequest\"G\n\x15QueryPositionResponse\x12\x14\n\x0craw_position\x18\x01 \x01(\x05\x12\x18\n\x10max_raw_position\x18\x02 \x01(\x05\"@\n\x12SetPositionRequest\x12\x14\n\x0craw_position\x18\x01 \x01(\x05\x12\x14\n\x0cpct_position\x18\x02 \x01(\x02\"1\n\x0eStatusResponse\x12\r\n\x05rcode\x18\x01 \x01(\x05\x12\x10\n\x08\x64iag_msg\x18\x02 \x01(\t2\xa5\x01\n\x12ThroughputRenderer\x12L\n\rQueryPosition\x12\x1b.tpmon.QueryPositionRequest\x1a\x1c.tpmon.QueryPositionResponse\"\x00\x12\x41\n\x0bSetPosition\x12\x19.tpmon.SetPositionRequest\x1a\x15.tpmon.StatusResponse\"\x00\x62\x06proto3')
)




_QUERYPOSITIONREQUEST = _descriptor.Descriptor(
  name='QueryPositionRequest',
  full_name='tpmon.QueryPositionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=44,
)


_QUERYPOSITIONRESPONSE = _descriptor.Descriptor(
  name='QueryPositionResponse',
  full_name='tpmon.QueryPositionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_position', full_name='tpmon.QueryPositionResponse.raw_position', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_raw_position', full_name='tpmon.QueryPositionResponse.max_raw_position', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=117,
)


_SETPOSITIONREQUEST = _descriptor.Descriptor(
  name='SetPositionRequest',
  full_name='tpmon.SetPositionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_position', full_name='tpmon.SetPositionRequest.raw_position', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pct_position', full_name='tpmon.SetPositionRequest.pct_position', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=183,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='tpmon.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rcode', full_name='tpmon.StatusResponse.rcode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diag_msg', full_name='tpmon.StatusResponse.diag_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=234,
)

DESCRIPTOR.message_types_by_name['QueryPositionRequest'] = _QUERYPOSITIONREQUEST
DESCRIPTOR.message_types_by_name['QueryPositionResponse'] = _QUERYPOSITIONRESPONSE
DESCRIPTOR.message_types_by_name['SetPositionRequest'] = _SETPOSITIONREQUEST
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryPositionRequest = _reflection.GeneratedProtocolMessageType('QueryPositionRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYPOSITIONREQUEST,
  __module__ = 'tpmon_pb2'
  # @@protoc_insertion_point(class_scope:tpmon.QueryPositionRequest)
  ))
_sym_db.RegisterMessage(QueryPositionRequest)

QueryPositionResponse = _reflection.GeneratedProtocolMessageType('QueryPositionResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYPOSITIONRESPONSE,
  __module__ = 'tpmon_pb2'
  # @@protoc_insertion_point(class_scope:tpmon.QueryPositionResponse)
  ))
_sym_db.RegisterMessage(QueryPositionResponse)

SetPositionRequest = _reflection.GeneratedProtocolMessageType('SetPositionRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETPOSITIONREQUEST,
  __module__ = 'tpmon_pb2'
  # @@protoc_insertion_point(class_scope:tpmon.SetPositionRequest)
  ))
_sym_db.RegisterMessage(SetPositionRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATUSRESPONSE,
  __module__ = 'tpmon_pb2'
  # @@protoc_insertion_point(class_scope:tpmon.StatusResponse)
  ))
_sym_db.RegisterMessage(StatusResponse)



_THROUGHPUTRENDERER = _descriptor.ServiceDescriptor(
  name='ThroughputRenderer',
  full_name='tpmon.ThroughputRenderer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=237,
  serialized_end=402,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryPosition',
    full_name='tpmon.ThroughputRenderer.QueryPosition',
    index=0,
    containing_service=None,
    input_type=_QUERYPOSITIONREQUEST,
    output_type=_QUERYPOSITIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetPosition',
    full_name='tpmon.ThroughputRenderer.SetPosition',
    index=1,
    containing_service=None,
    input_type=_SETPOSITIONREQUEST,
    output_type=_STATUSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_THROUGHPUTRENDERER)

DESCRIPTOR.services_by_name['ThroughputRenderer'] = _THROUGHPUTRENDERER

# @@protoc_insertion_point(module_scope)
